# Site settings
title:              Nathan Corwin Portfolio
email:              nathancorwin2015@u.northwestern.edu
description:        "Portfolio for Nathan Corwin, a student in the MSR program at Northwestern University"
url:                "http://localhost:4000"
baseurl:	    	/


# File structure settings
image_path:         public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
